### ISSUE TITLE
After your SignalR web project update Android app not working 

### ISSUE THREAD

**Issue by DarshitDsp** [AKouki/SignalR-Chat.Mobile#2]
Now after credential enter in AsyncLoginTask Cookie does not get .AspNet.ApplicationCookie data 
currently it get only two cookie data 
1.AspNetCore.Antiforgery.e4LYVp6EJBs 
[version: 0][name: .AspNetCore.Antiforgery.e4LYVp6EJBs][value: CfDJ8KQ-c6UzPLRKvQHwSPRaIRC6CyjBD_koj4rtlMJpXhF1ZwanKvtWyxUuB-5A7gxyj3B4P5akJtBr7uX7cDZ73EcMRYNVviFvDyAZNUF16Hc8B3CGBOtDCPxKiTOMld4d1U-DAN5OkBAvZdznLWhhOUA][domain: owa.ssminfotech.com][path: /][expiry: null]
2 .AspNetCore.Identity.Application
[version: 0][name: .AspNetCore.Identity.Application][value: CfDJ8KQ-c6UzPLRKvQHwSPRaIRCM6xWGiR2HZ9UVN_638_ZfNQsBLZo9pbHAqFeRCXhH493bhu0Ev09okJ94k97oXqBAi8eOV2PZqSJ1GYuYS8jJvztoOHGSVbaEo49dRKvGblHbjcataoPp37dnusV9Z0gf-uUv9Gvw_EJi9-8rC38mREAPpsmEBxhHTcXJxM1HQflOaNTFE3jo0ohFkdY3kkBavlhUSvx9jbsR6CW4KEEdRcmbFbUuFhUX2Fx9mxJIEy4zXaFHtdIgk3E3mYSEwPsz3MwX00lO-hk0lU8kJ082G7JBqYy5mvLVzqbiE0urSboOFcngHvE6iW3_dKBfuuLV46rNSooVhtaHMi-9L4W3Wj6kr7ENhhWpEIRUciJ-hLlYJ6Ng9QOh0eJWiyCPpoLG4AxSbHYy9IZyWDla7YGk9iFCK12UGeab7ecCkeNEdTmPmuWuvIjVxVeEbUf-77sBAIVTkSKwbjom_fAsK-MZU-Q8J8GLlKOiikE2sjHIctZRU-wwIx88L_cK_BDSzo2ey2ridROwi53FDf5x-j2gcHsO2VYaMer5RAtSR58FWZTtui2wkkEMzv7wXq39O-WbIzCs92fV6NUtS6J14pCJ][domain: owa.ssminfotech.com][path: /][expiry: null]

**Comment by AKouki** [comment]
The new updated version (.NET Core) does not support mobile application. You will need the .net framework version of the project which is in different branch called netframework.

**Comment by DarshitDsp** [comment]
can you please share that link

**Comment by AKouki** [comment]
https://github.com/AKouki/SignalR-Chat/tree/netframework
