### ISSUE TITLE
service problem

### ISSUE THREAD

**Issue by fukemy** [AKouki/SignalR-Chat.Mobile#3]
hi, after new android O, all service must be startforeground and show notification to visible to user, do u have best solution for this?

**Comment by AKouki** [comment]
Hello, this is an old project and i am not maintaing it. Maby in the feature i will update it to latest android version. 

What exactly is the problem? can you please show me a screenshot?

**Comment by fukemy** [comment]
yeah. im trying to test project, but i think it work normally when we only need signalr service run when app is active. Thanks

**Comment by AKouki** [comment]
This app was created to send/receive messages while the app is open. After the Android Oreo changes you could use startForeground for SDK >= O after the bindService.
